<h3> Numpy array are used widely for images and other datas</h3>

In [1]:
import numpy as np

In [2]:
np.__version__

'1.26.0'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
l=[1,2,3,4,5] #python list
np.array(l) #numpy array

array([1, 2, 3, 4, 5])

In [5]:
type(np.array(l))  #ndarray means n dimensional array, 1d, 2d, 3d

numpy.ndarray

In [6]:
arr=np.array(["abhi"])
type(arr) #type is still saying numpy.ndarray, but that is for dimension
arr

array(['abhi'], dtype='<U4')

a numpy array only stores same type of data, if string and numbers two data types are entered, it becomes a string array (type <u11)

In [7]:
arr1=np.array(["abhi", "nandan", 1, 2])
arr1

array(['abhi', 'nandan', '1', '2'], dtype='<U11')

2D array

In [8]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
arr1.ndim

2

matrix is subclass of ndarray

In [10]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [11]:
# mat = np.matrix([[[1, 2], [5, 6], [7, 8]]]) #matris will be by default 2d
# mat

In [12]:
np.array([[[1, 2], [5, 6], [7, 8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

More ways to convert to array

In [13]:
np.asarray([[[1, 2], [5, 6], [7, 8]]]) #same as np.array

array([[[1, 2],
        [5, 6],
        [7, 8]]])

np.asanyaraay: if the input is a subclass of ndarray, like matrix, it won't do anyting to it. Otherwise, it will change the input to an ndarray

asarray or array, will convert any input, even a matrix, to a ndarray

In [14]:
np.asanyarray([[[1, 2], [5, 6], [7, 8]]]) #Convert the input to an ndarray, but pass ndarray subclasses through.


array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [15]:
mat = np.matrix([[1, 2], [5, 6], [7, 8]])
np.asanyarray(mat) #no change

matrix([[1, 2],
        [5, 6],
        [7, 8]])

In [16]:
np.array(mat) #CONVERTED TO 2D ARRAY    

array([[1, 2],
       [5, 6],
       [7, 8]])

In [17]:
t = ([1, 2, 3], [4, 5, 6])

In [18]:
np.asanyarray(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a = 5
np.array(a)

array(5)

Deep and Shallow copy in Numpy

In [20]:
arr=np.array(l)
arr[0]

1

Remember there is a difference between memory reference in lists and np arrays.

Shallow copy

In [21]:
a=arr  #both pointing to same memory location
a[0]=1000  
arr

array([1000,    2,    3,    4,    5])

In [22]:
a

array([1000,    2,    3,    4,    5])

Deep copy, change in one doesn't affect another ndarray

In [23]:
b=a.copy()
b

array([1000,    2,    3,    4,    5])

In [24]:
a[0]=0
b

array([1000,    2,    3,    4,    5])

In [25]:
arr

array([0, 2, 3, 4, 5])

More functions to generate array

In [26]:
def testfunc(i,j):
    return i*j

In [27]:
np.fromfunction(testfunc, shape=(4,4))  #i and j are indices of the matrix

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [28]:
np.fromfunction(lambda i,j: i==j, shape=(4,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [29]:
arr=np.array([1,2,3,4,5])

In [30]:
print(arr.shape)
print(arr.size)

(5,)
5


In [31]:
print(arr1.shape)
print(arr.size)

(2, 3)
5


In [32]:
type(i for i in range(5))

generator

In [33]:
print(type(range(5)))
range(5)


<class 'range'>


range(0, 5)

In [34]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [35]:
list(range(5))

[0, 1, 2, 3, 4]

In [36]:
type(i*i for i in range(5))

generator

In [37]:
(i for i in range(5))

<generator object <genexpr> at 0x000001D76F591D80>

In [38]:
iterable=(i for i in range(5))

integer array from generator object

In [39]:
np.fromiter(iterable, dtype=int)  

array([0, 1, 2, 3, 4])

float array from the same generator

In [40]:
np.fromiter(iterable, float) #notice that the generator has already been run through, and is now empty

array([], dtype=float64)

In [41]:
np.fromiter((i*i for i in range(5)), float)

array([ 0.,  1.,  4.,  9., 16.])

Array from a String

In [42]:
np.fromstring('23 24 25', sep=" ")

array([23., 24., 25.])

In [43]:
np.fromstring("a b c", sep=" ") #so in future we can only use numbers i guess

C:\Users\Pc\AppData\Local\Temp\ipykernel_5896\572259970.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("a b c", sep=" ") #so in future we can only use numbers i guess


array([], dtype=float64)

In [44]:
print(arr)
print(arr.dtype)
print(arr.shape)

[1 2 3 4 5]
int32
(5,)


np.arange is similar to the range function except that it generates a numpy ndarray and unlike range fucntion, it also works with floats

In [45]:
np.arange(start=10, stop=20, step=2)

array([10, 12, 14, 16, 18])

In [46]:
np.arange(1,5)

array([1, 2, 3, 4])

In [47]:
np.arange(-0.3, -1)

array([], dtype=float64)

In [48]:
np.arange(-0.3, 1, 0.2)

array([-0.3, -0.1,  0.1,  0.3,  0.5,  0.7,  0.9])

<h3>np.linespace.</h3>
Return evenly spaced numbers over a specified interval.
<br> <br>
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [49]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [50]:
np.linspace(156,359, dtype=float, num=69)

array([156.        , 158.98529412, 161.97058824, 164.95588235,
       167.94117647, 170.92647059, 173.91176471, 176.89705882,
       179.88235294, 182.86764706, 185.85294118, 188.83823529,
       191.82352941, 194.80882353, 197.79411765, 200.77941176,
       203.76470588, 206.75      , 209.73529412, 212.72058824,
       215.70588235, 218.69117647, 221.67647059, 224.66176471,
       227.64705882, 230.63235294, 233.61764706, 236.60294118,
       239.58823529, 242.57352941, 245.55882353, 248.54411765,
       251.52941176, 254.51470588, 257.5       , 260.48529412,
       263.47058824, 266.45588235, 269.44117647, 272.42647059,
       275.41176471, 278.39705882, 281.38235294, 284.36764706,
       287.35294118, 290.33823529, 293.32352941, 296.30882353,
       299.29411765, 302.27941176, 305.26470588, 308.25      ,
       311.23529412, 314.22058824, 317.20588235, 320.19117647,
       323.17647059, 326.16176471, 329.14705882, 332.13235294,
       335.11764706, 338.10294118, 341.08823529, 344.07

<h3>numpy.logspace</h3>
<a > syntax</a>
<p>numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0)[source] </p>
Return numbers spaced evenly on a log scale.

In linear space, the sequence starts at base ** start (base to the power of start) and ends with base ** stop

In [51]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

<h3>np.zeros</h3>

In [52]:
np.zeros(shape=5)

array([0., 0., 0., 0., 0.])

In [53]:
np.zeros(shape=(4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [54]:
np.zeros((4,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [55]:
np.zeros((4,2,3)).shape

(4, 2, 3)

<h3>np.ones</h3>

In [56]:
np.ones(shape=(3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [57]:
arr=np.ones((2,2))
arr

array([[1., 1.],
       [1., 1.]])

<a>Baic mathematic operations on numpy arrays and comparison to python lists </a>

In [58]:
l=[1,2,4]
l*3

[1, 2, 4, 1, 2, 4, 1, 2, 4]

In [59]:
arr*3

array([[3., 3.],
       [3., 3.]])

In [60]:
# l+5  #does not work
arr+5

array([[6., 6.],
       [6., 6.]])

In [61]:
np.array(l)+5

array([6, 7, 9])

In [62]:
np.matrix(l)

matrix([[1, 2, 4]])

In [63]:
np.matrix(l)*2

matrix([[2, 4, 8]])