<h5>Here we explore some more array generating numpy functions. and np.random class, reshaping arrays, etc.</h5>

In [1]:
import numpy as np
import random #np came up with its own functions of generating random numbers
#and thus, we started using np.random class istead of the original random library.
import pandas as pd

In [2]:
arr=np.ones(shape=(3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
arr+5  #goes through every number and adds 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

np.empty() is a very unique function, gives you a nd array of random values. It's weird cause it is giving an array of elements being all 6, the same as arr+5. 

In [4]:
# np.ones((100000,10000))*5 #takes 12 seconds
np.empty((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

But here it stops giving 6 and gives random values

In [5]:
np.empty((4,5))

array([[2.11398144e-307, 1.89144180e-307, 2.11392372e-307,
        6.89795644e-307, 3.56042035e-307],
       [1.33509117e-306, 1.69119873e-306, 1.33509389e-306,
        8.34443864e-308, 1.00132822e-307],
       [6.89795644e-307, 2.33645997e-307, 5.56296306e-307,
        3.11520356e-307, 4.67291993e-307],
       [2.78148153e-307, 1.50198172e-307, 4.45047026e-307,
        1.61323712e-307, 3.31023983e-322]])

In [6]:
arr+7

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

#same shizz again. gives 8, same as arr+7

In [7]:
np.empty(shape=(3,4))

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [8]:
np.empty((3,4), int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [9]:
np.empty(3)

array([1.02300606e-311, 1.02280197e-311, 1.02300605e-311])

In [10]:
np.empty((3,4), float)

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [11]:
np.empty((3,4), float) #weird, sometimes it returns random numbers


array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

np.eye(), Return a 2-D array with ones on the diagonal and zeros elsewhere

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.eye(3,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [14]:
np.eye(3, dtype=str)

array([['1', '', ''],
       ['', '1', ''],
       ['', '', '1']], dtype='<U1')

making a dataframe from an array

In [15]:
pd.DataFrame(np.eye(3,3, dtype=int))

0  1  2
0  1  0  0
1  0  1  0
2  0  0  1

In [16]:
random.choice(seq=[1,2,4,4,5,6])  #choose any one

6

In [17]:
random.choice((1,2,3,4,5,6,7,8))  

3

random.randrange to generate any number between the given range,itegers only.

In [18]:
print(random.randrange(1,10.0,1))  #only 1,3,5,7,9
print(random.randrange(5))  #0,1,2,3 or 4
print(random.randrange(1,10))  #1 to 9

4
4
4


C:\Users\Pc\AppData\Local\Temp\ipykernel_12432\4165053056.py:1: DeprecationWarning: non-integer arguments to randrange() have been deprecated since Python 3.10 and will be removed in a subsequent version
  print(random.randrange(1,10.0,1))  #only 1,3,5,7,9


In [19]:
l=[1,2,3,4,5,123,43,453]
random.shuffle(l)

In [20]:
print(l)
print(l[2])

[43, 1, 3, 5, 123, 2, 4, 453]
3


In [21]:
random.uniform(5,15)  #get a random number between the range, each number has an equal probability

10.407054876637254

<h2>np.random </h2>

In [22]:
np.random.rand() #return a number between 0 and 1, excluding one

0.5360202479013286

In [23]:
np.random.rand(3,2)  #numbers between 0 and 1, 2d array

array([[0.08982094, 0.03003927],
       [0.19164563, 0.72955078],
       [0.27874915, 0.89260584]])

In [24]:
np.random.rand(5)  #1d array of size 5

array([0.78791176, 0.7873377 , 0.52030075, 0.92800347, 0.79695437])

randn: Return a sample (or samples) from the “standard normal” distribution.

In [25]:
np.random.randn(1)

array([1.56965442])

In [26]:
np.random.randn(4)

array([-1.02983672, -0.27838509,  1.68515784, -2.01521171])

In [27]:
l=np.random.randn(4)

sum=0
for i in l:
    sum+=i
print(sum/4)  #so this shows that the numbers are generated from 
# a normal distribution of mean 0 and std 1 but that does not mean that the values generated
#have mean 0 and std1

0.10997959884109851


In [28]:
arr=np.random.randn(3,4,5,6,1)  #5d array
arr

array([[[[[-0.08538285],
          [ 0.17352919],
          [ 0.62437673],
          [-0.18395786],
          [ 0.7955869 ],
          [-0.2831058 ]],

         [[-1.03087553],
          [-0.31438115],
          [-1.1918492 ],
          [ 1.72012236],
          [-0.86817361],
          [ 1.00717937]],

         [[ 1.63676995],
          [-2.72051733],
          [-1.29179354],
          [ 1.20111387],
          [-0.17133965],
          [-0.0907068 ]],

         [[ 0.40985925],
          [-0.35869334],
          [-0.67023212],
          [-0.74155483],
          [ 1.44574581],
          [ 0.9154201 ]],

         [[ 0.19962733],
          [ 1.47706217],
          [ 0.7365861 ],
          [-0.49809207],
          [-0.31569612],
          [-1.15834058]]],


        [[[-0.17625317],
          [-0.62958755],
          [ 0.96329962],
          [ 0.39789747],
          [ 1.24328776],
          [ 1.91726907]],

         [[ 0.43898459],
          [-0.49966454],
          [ 0.19522837],
          [

In [29]:
arr.shape

(3, 4, 5, 6, 1)

np.random.random_sample(), same as np.random.rand()

In [30]:
np.random.random_sample()

0.30220739306520195

In [31]:
np.random.random_sample((3))

array([0.85233041, 0.86047067, 0.74951981])

In [32]:
np.random.random_sample(size=(3,4))

array([[0.10870863, 0.28432871, 0.73919187, 0.38338033],
       [0.37016989, 0.08733408, 0.39376984, 0.31132728],
       [0.12709303, 0.69345622, 0.86996502, 0.10036674]])

In [33]:
np.random.rand()

0.4305123535510077

np.random.randit(size=None)  works just like rand() except it returns integers between the passed range

In [34]:
np.random.randint(1,6, size=(10,2)) #np.random class takes size, where as normally, numpy uses shape.

array([[4, 1],
       [2, 5],
       [4, 5],
       [1, 4],
       [2, 1],
       [5, 4],
       [2, 4],
       [4, 1],
       [5, 3],
       [1, 2]])

In [35]:
arr=np.random.randint(1,5, size=(3,4))
arr

array([[2, 2, 3, 2],
       [3, 2, 3, 4],
       [3, 2, 2, 2]])

In [36]:
arr.size

12

In [37]:
arr.shape

(3, 4)

In [38]:
arr.ndim

2

In [39]:
arr

array([[2, 2, 3, 2],
       [3, 2, 3, 4],
       [3, 2, 2, 2]])

<h3>Reshaping arrays</h3>
<p>A lot of ml models will expect data only in a particular shape, during those times these functions come in handy.</p>

In [40]:
arr.reshape(4,3) #notice how it is reshaping the array arr, it goes through each row of the original and places the elements as they come, into each row of the new shape. One after another.

# arr.reshape(5,6) #gives an error. total 30 elements now to be filled.

array([[2, 2, 3],
       [2, 3, 2],
       [3, 4, 3],
       [2, 2, 2]])

In [41]:
arr  #original array doesn't get changed.

array([[2, 2, 3, 2],
       [3, 2, 3, 4],
       [3, 2, 2, 2]])

In [42]:
arr.reshape(12,)  # 1D array if no column number is passed.

array([2, 2, 3, 2, 3, 2, 3, 4, 3, 2, 2, 2])

In [43]:
arr.reshape(12,1)  # 2D array if column number is passed.

array([[2],
       [2],
       [3],
       [2],
       [3],
       [2],
       [3],
       [4],
       [3],
       [2],
       [2],
       [2]])

In [44]:
arr.reshape(2,2,3)  #3d array

array([[[2, 2, 3],
        [2, 3, 2]],

       [[3, 4, 3],
        [2, 2, 2]]])

In [45]:
arr.reshape(2,3,2)

array([[[2, 2],
        [3, 2],
        [3, 2]],

       [[3, 4],
        [3, 2],
        [2, 2]]])

let's say you want only 4 rows, but you don't know how many columns you want, or vice versa, just pass -1 in the other field. This is extremely useful for passing data in a certain format for a data with a huge shape.

In [46]:
arr.reshape(4,-1)

array([[2, 2, 3],
       [2, 3, 2],
       [3, 4, 3],
       [2, 2, 2]])

In [47]:
arr.reshape(-1, 3)

array([[2, 2, 3],
       [2, 3, 2],
       [3, 4, 3],
       [2, 2, 2]])

In [48]:
# arr.reshape(5, -1) #gives an error, cause no pair with 5 in it would fit.

works with more than 2D as well.

In [49]:
arr.reshape(2,2,-1)

array([[[2, 2, 3],
        [2, 3, 2]],

       [[3, 4, 3],
        [2, 2, 2]]])

In [50]:
arr.reshape(1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3)

array([[[[[[[[[[[[2, 2, 3],
                 [2, 3, 2]],

                [[3, 4, 3],
                 [2, 2, 2]]]]]]]]]]]])

arr.reshape is a shallow copy

In [51]:
arr2=arr.reshape(12,-1)
arr2

array([[2],
       [2],
       [3],
       [2],
       [3],
       [2],
       [3],
       [4],
       [3],
       [2],
       [2],
       [2]])

In [52]:
arr2.shape

(12, 1)

In [53]:
arr2[4,0]=199
arr2

array([[  2],
       [  2],
       [  3],
       [  2],
       [199],
       [  2],
       [  3],
       [  4],
       [  3],
       [  2],
       [  2],
       [  2]])

In [54]:
arr #changes made in arr2 are also being reflected in arr.

array([[  2,   2,   3,   2],
       [199,   2,   3,   4],
       [  3,   2,   2,   2]])

.base property of the reshape function tells us the original array which we are reshaping, that is arr

In [55]:
arr

array([[  2,   2,   3,   2],
       [199,   2,   3,   4],
       [  3,   2,   2,   2]])

In [56]:
arr.reshape(12,1).base #returns the original arr that is being reshaped, i.e., arr

array([[  2,   2,   3,   2],
       [199,   2,   3,   4],
       [  3,   2,   2,   2]])

In [57]:
arr2.reshape(6,-1).base  #arr2 is being reshaped but since it is a shallow copy of arr, arr is returned by .base

array([[  2,   2,   3,   2],
       [199,   2,   3,   4],
       [  3,   2,   2,   2]])

In [58]:
lis=[1,2,3,4]

In [59]:
arr=np.asarray(lis)
arr

array([1, 2, 3, 4])

In [60]:
arr.ndim #1d array

1

In [61]:
arr2=np.array([[1,2], [3,4]])
arr2.ndim

2

In [62]:
arr3=np.zeros((3,4))
arr3.ndim

2

<a>Very important</a>

In [63]:
arr3=np.zeros(shape=(1,3,4))  # 3 rows and 4 columns, +1 extra dimension!!
#it's hard to visualize arrays
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [64]:
arr3.ndim

3

In [65]:
arr3.shape

(1, 3, 4)

3 rows and 4 columns, that makes a 2d array.
+1d +1d


In [66]:
arr4=np.zeros(shape=(1,1,3,4))
arr4  

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

what about shape=2,3,4.

In [67]:
arr3=np.zeros(shape=(2,3,4))  # 3 rows and 4 columns, that's 2d, 2 times that matrix.
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [68]:
np.zeros(shape=(3,3,4)) # 3 rows and 4 column, 3 times

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [69]:
arr4=np.zeros(shape=(2,2,3,4))
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])