<h5>We will perform some mathematical operations on numpy arrays. Like addition suntraction, and slicing for n-dimension arrays, etc </h5>

In [1]:
import numpy as np

In [2]:
arr1=np.random.randint(1,10, (5,6))

In [3]:
arr1

array([[6, 3, 5, 1, 6, 5],
       [9, 1, 2, 2, 7, 5],
       [5, 9, 7, 2, 6, 7],
       [9, 1, 4, 1, 8, 6],
       [9, 9, 7, 2, 6, 8]])

Suppose we want to know which values are greater than 5.

In [4]:
arr1>5 #this will go through each element index wise and check for conditon.

array([[ True, False, False, False,  True, False],
       [ True, False, False, False,  True, False],
       [False,  True,  True, False,  True,  True],
       [ True, False, False, False,  True,  True],
       [ True,  True,  True, False,  True,  True]])

What if we want the values that are greater 5 as an array.

In [5]:
arr1[arr1 > 5]

array([6, 6, 9, 7, 9, 7, 6, 7, 9, 8, 6, 9, 9, 7, 6, 8])

In [6]:
arr=arr1[arr1<5]

In [7]:
arr[1]

1

In [8]:
arr1

array([[6, 3, 5, 1, 6, 5],
       [9, 1, 2, 2, 7, 5],
       [5, 9, 7, 2, 6, 7],
       [9, 1, 4, 1, 8, 6],
       [9, 9, 7, 2, 6, 8]])

In [9]:
arr1[1]  #gives the second row

array([9, 1, 2, 2, 7, 5])

In [10]:
arr1[1:3] #gives the second and third row. 

array([[9, 1, 2, 2, 7, 5],
       [5, 9, 7, 2, 6, 7]])

accessing the first element.

In [11]:
print(arr1[0][0])
#or
print(arr1[0,0])

6
6


In [12]:
arr1

array([[6, 3, 5, 1, 6, 5],
       [9, 1, 2, 2, 7, 5],
       [5, 9, 7, 2, 6, 7],
       [9, 1, 4, 1, 8, 6],
       [9, 9, 7, 2, 6, 8]])

accessing the 3rd, 4th and 5th element of first row

In [13]:
arr1[0, [2,3,4]]

array([5, 1, 6])

3rd row to 4th row, and 3rd and 4th column 

In [14]:
arr1[2:4, [2,3]]

array([[7, 2],
       [4, 1]])

In [15]:
arr1

array([[6, 3, 5, 1, 6, 5],
       [9, 1, 2, 2, 7, 5],
       [5, 9, 7, 2, 6, 7],
       [9, 1, 4, 1, 8, 6],
       [9, 9, 7, 2, 6, 8]])

pass two ranges, one for rows, second for columns

In [16]:
arr1[0:5, 1:5]

array([[3, 5, 1, 6],
       [1, 2, 2, 7],
       [9, 7, 2, 6],
       [1, 4, 1, 8],
       [9, 7, 2, 6]])

In [17]:
arr1[[0,3], 1:5] #first and 4th row

array([[3, 5, 1, 6],
       [1, 4, 1, 8]])

In [18]:
arr1[[3,4]] #4th and 5th row

array([[9, 1, 4, 1, 8, 6],
       [9, 9, 7, 2, 6, 8]])

In [19]:
arr1[0:4]

array([[6, 3, 5, 1, 6, 5],
       [9, 1, 2, 2, 7, 5],
       [5, 9, 7, 2, 6, 7],
       [9, 1, 4, 1, 8, 6]])