In [2]:
import numpy as np

In [3]:
arr1=np.random.randint(1,3, (3,3))
arr2=np.random.randint(1,3, (3,3))

In [4]:
arr1

array([[2, 1, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [5]:
arr2

array([[1, 2, 2],
       [2, 2, 2],
       [2, 2, 1]])

#### Basic Math Operations

In [6]:
arr1+arr2

array([[3, 3, 4],
       [4, 4, 3],
       [3, 3, 2]])

In [7]:
arr1-arr2

array([[ 1, -1,  0],
       [ 0,  0, -1],
       [-1, -1,  0]])

In [8]:
arr1*arr2  #this is not matrix multiplication but normal matrix multiplication

array([[2, 2, 4],
       [4, 4, 2],
       [2, 2, 1]])

#### Matrix Multiplication

In [9]:
arr1@arr2 #weird shit

array([[ 8, 10,  8],
       [ 8, 10,  9],
       [ 5,  6,  5]])

In [10]:
arr1/arr2  #index-wise division

array([[2. , 0.5, 1. ],
       [1. , 1. , 0.5],
       [0.5, 0.5, 1. ]])

In [11]:
# 5/0  #division by zero array

numpy doesn't do this.

In [12]:
arr1/0  

C:\Users\Pc\AppData\Local\Temp\ipykernel_17932\1935447961.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

what if one of the elements in a matrix is zero and then we divide.

In [13]:
arr2[0,0]=0
arr2

array([[0, 2, 2],
       [2, 2, 2],
       [2, 2, 1]])

In [14]:
import warnings
warnings.filterwarnings("ignore")
arr1/arr2  #that particular index number which in being divided by zero says inf

array([[inf, 0.5, 1. ],
       [1. , 1. , 0.5],
       [0.5, 0.5, 1. ]])

In [15]:
arr3=arr1/arr2
type(arr3[0,0])  # the inf which looks like a string is a float type.

numpy.float64

In [16]:
arr1=np.random.randint(20,100,size=(4,4))
arr1

array([[80, 79, 21, 44],
       [31, 97, 20, 70],
       [81, 69, 27, 47],
       [44, 37, 57, 77]])

square root

In [17]:
np.sqrt(arr1)

array([[8.94427191, 8.88819442, 4.58257569, 6.63324958],
       [5.56776436, 9.8488578 , 4.47213595, 8.36660027],
       [9.        , 8.30662386, 5.19615242, 6.8556546 ],
       [6.63324958, 6.08276253, 7.54983444, 8.77496439]])

In [18]:
np.log10(arr1)

array([[1.90308999, 1.89762709, 1.32221929, 1.64345268],
       [1.49136169, 1.98677173, 1.30103   , 1.84509804],
       [1.90848502, 1.83884909, 1.43136376, 1.67209786],
       [1.64345268, 1.56820172, 1.75587486, 1.88649073]])

In [19]:
np.exp(arr1)   # power euler's constant should be raised to get the values in the arr1

array([[5.54062238e+34, 2.03828107e+34, 1.31881573e+09, 1.28516001e+19],
       [2.90488497e+13, 1.33833472e+42, 4.85165195e+08, 2.51543867e+30],
       [1.50609731e+35, 9.25378173e+29, 5.32048241e+11, 2.58131289e+20],
       [1.28516001e+19, 1.17191424e+16, 5.68572000e+24, 2.75851345e+33]])

In [20]:
np.exp2(arr1)

array([[1.20892582e+24, 6.04462910e+23, 2.09715200e+06, 1.75921860e+13],
       [2.14748365e+09, 1.58456325e+29, 1.04857600e+06, 1.18059162e+21],
       [2.41785164e+24, 5.90295810e+20, 1.34217728e+08, 1.40737488e+14],
       [1.75921860e+13, 1.37438953e+11, 1.44115188e+17, 1.51115727e+23]])

finding minimum values

In [21]:
np.min(arr1)

20

In [22]:
np.max(arr1)

97

In [23]:
arr3=np.random.randint(1,20, size=(3,3,4))

In [24]:
arr3

array([[[ 2, 19,  6,  8],
        [18,  2,  2,  4],
        [ 5,  4,  8, 14]],

       [[ 1, 14,  5, 19],
        [16, 15, 16, 18],
        [16, 14, 10, 19]],

       [[ 9, 11,  4,  6],
        [ 7, 14,  7, 10],
        [ 7, 19,  4,  8]]])

In [25]:
np.max(arr3)

19

.flatten() is used to transfer any array to 1D, it goes row wise through the original array and adds each element one by one to a 1D array.

In [26]:
arr3.flatten()

array([ 2, 19,  6,  8, 18,  2,  2,  4,  5,  4,  8, 14,  1, 14,  5, 19, 16,
       15, 16, 18, 16, 14, 10, 19,  9, 11,  4,  6,  7, 14,  7, 10,  7, 19,
        4,  8])

#### Adding elements column wise and row wise

In [27]:
arr=np.random.randint(1,5,size=(3,3))
arr

array([[1, 1, 4],
       [2, 4, 2],
       [4, 2, 3]])

In [28]:
np.sum(arr, axis=0)  #row wise addition, so basically it moves from one row to next, column is same.
#though it seems column-wise, it is row wise. !!

array([7, 7, 9])

In [29]:
np.sum(arr, axis=1) #column wise additon, row remains same

array([6, 8, 9])

##### Expand_dims
increases the dimension of an array by 1D <br>
use cases: image processing

In [30]:
arr=np.array([1,2,3,4])
np.expand_dims(arr, axis=0)#row-wise, horizontal expansion

array([[1, 2, 3, 4]])

In [31]:
np.expand_dims(arr, axis=1)  #column wise, vertical expansion
#so each row element, becomes a row of it's own.

array([[1],
       [2],
       [3],
       [4]])

In [32]:
arr1

array([[80, 79, 21, 44],
       [31, 97, 20, 70],
       [81, 69, 27, 47],
       [44, 37, 57, 77]])

In [33]:
arr1.ndim

2

In [34]:
arr1_expanded=np.expand_dims(arr1, axis=0) 
print(arr1_expanded)
print(arr1_expanded.ndim)  #dimension increases

[[[80 79 21 44]
  [31 97 20 70]
  [81 69 27 47]
  [44 37 57 77]]]
3


working of axis=1 is similar to increasing the number of one's on the size parameter of randit

In [35]:
np.random.randint(1,10, size=(1,3,3))

array([[[9, 5, 9],
        [9, 6, 1],
        [5, 6, 5]]])

In [36]:
np.random.randint(1,10, size=(1,1,3,3))

array([[[[5, 3, 9],
         [3, 6, 8],
         [2, 1, 2]]]])

In [37]:
np.random.randint(1,10, size=(1,1,1,3,3))

array([[[[[2, 2, 7],
          [5, 9, 2],
          [3, 6, 8]]]]])

In [38]:
np.expand_dims(arr1_expanded, axis=0).ndim

4

np.expand_dims() with axis=1

In [39]:
arr1_expanded_axis_1=np.expand_dims(arr1, axis=1) #this is actually increasing the number of rows in the outer array.
arr1_expanded_axis_1

array([[[80, 79, 21, 44]],

       [[31, 97, 20, 70]],

       [[81, 69, 27, 47]],

       [[44, 37, 57, 77]]])

In [40]:
arr1_expanded_axis_1.ndim

3

In [41]:
arr1_expanded_axis_2=np.expand_dims(arr1_expanded_axis_1, axis=1)
arr1_expanded_axis_2

array([[[[80, 79, 21, 44]]],


       [[[31, 97, 20, 70]]],


       [[[81, 69, 27, 47]]],


       [[[44, 37, 57, 77]]]])

In [42]:
arr1_expanded_axis_2.ndim

4

In [43]:
np.expand_dims(arr1_expanded_axis_2, axis=1)

array([[[[[80, 79, 21, 44]]]],



       [[[[31, 97, 20, 70]]]],



       [[[[81, 69, 27, 47]]]],



       [[[[44, 37, 57, 77]]]]])

In [44]:
np.expand_dims(arr1_expanded_axis_2, axis=1).ndim

5