broad casting on tv or radio is like spreading info among the population. Similarly in np, it means telling something to an array and all the values inside are you population.

In [13]:
import numpy as np

In [14]:
arr=np.zeros(shape=(3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
arr+5 #every array element is affected.

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [16]:
a=np.array([1,2,3,4])

In [17]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

what about a normal list

In [18]:
a=[1,2,3,4]
arr+a  #list added to every row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

what about something with 3 columns

In [19]:
a.append(5)
a

[1, 2, 3, 4, 5]

In [20]:
# arr+a #gives an error, could not be broadcasted together

what if a is a 2d array with one row itself

In [39]:
a=np.array([[1,2,3,4]])
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [41]:
a=np.array([[1,2,3,4],
            [5,6,7,8]])

In [42]:
# arr+a #gives an error

ValueError: operands could not be broadcast together with shapes (3,4) (2,4) 

##### Now Adding an array to values in each volumn using transpose of a matrix

In [44]:
a=np.array([1,2,3])
# arr+a.T #this gives an error as a.T does not exist as a is 1D

In [45]:
a=np.array([[1,2,3]])
a.T

array([[1],
       [2],
       [3]])

In [47]:
arr+a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])