In [144]:
import numpy as np

In [145]:
arr1 = np.random.randint(1, 10, (3, 4))
arr2 = np.random.randint(1, 10, (3, 4))

In [146]:
arr1

array([[9, 6, 5, 6],
       [6, 3, 9, 7],
       [3, 1, 6, 4]])

In [147]:
arr2

array([[3, 3, 2, 8],
       [5, 7, 3, 6],
       [4, 7, 5, 9]])

In [148]:
arr1+arr2

array([[12,  9,  7, 14],
       [11, 10, 12, 13],
       [ 7,  8, 11, 13]])

In [149]:
arr1/arr2

array([[3.        , 2.        , 2.5       , 0.75      ],
       [1.2       , 0.42857143, 3.        , 1.16666667],
       [0.75      , 0.14285714, 1.2       , 0.44444444]])

In [150]:
arr1-arr2

array([[ 6,  3,  3, -2],
       [ 1, -4,  6,  1],
       [-1, -6,  1, -5]])

In [151]:
arr1**arr2

array([[    729,     216,      25, 1679616],
       [   7776,    2187,     729,  117649],
       [     81,       1,    7776,  262144]])

In [152]:
arr1>arr2

array([[ True,  True,  True, False],
       [ True, False,  True,  True],
       [False, False,  True, False]])

### Numpy string functions

In [153]:
arr=np.array(["abhi", "nandan"])

In [154]:
arr

array(['abhi', 'nandan'], dtype='<U6')

In [155]:
np.char.upper(arr)

array(['ABHI', 'NANDAN'], dtype='<U6')

In [156]:
arr[0]=5
arr

array(['5', 'nandan'], dtype='<U6')

In [157]:
np.char.upper(arr)  #so it was a string array and 5 became a string

array(['5', 'NANDAN'], dtype='<U6')

In [158]:
arr[0]="abhi"

In [159]:
np.char.capitalize(arr)

array(['Abhi', 'Nandan'], dtype='<U6')

In [160]:
np.char.title(arr)

array(['Abhi', 'Nandan'], dtype='<U6')

### Mathematical Functions

In [161]:
arr

array(['abhi', 'nandan'], dtype='<U6')

In [162]:
np.sin(arr1)

array([[ 0.41211849, -0.2794155 , -0.95892427, -0.2794155 ],
       [-0.2794155 ,  0.14112001,  0.41211849,  0.6569866 ],
       [ 0.14112001,  0.84147098, -0.2794155 , -0.7568025 ]])

In [163]:
np.cos(arr1)

array([[-0.91113026,  0.96017029,  0.28366219,  0.96017029],
       [ 0.96017029, -0.9899925 , -0.91113026,  0.75390225],
       [-0.9899925 ,  0.54030231,  0.96017029, -0.65364362]])

In [164]:
np.tan(arr1)

array([[-0.45231566, -0.29100619, -3.38051501, -0.29100619],
       [-0.29100619, -0.14254654, -0.45231566,  0.87144798],
       [-0.14254654,  1.55740772, -0.29100619,  1.15782128]])

In [165]:
np.log10(arr1)

array([[0.95424251, 0.77815125, 0.69897   , 0.77815125],
       [0.77815125, 0.47712125, 0.95424251, 0.84509804],
       [0.47712125, 0.        , 0.77815125, 0.60205999]])

In [166]:
np.power(arr1, 3)

array([[729, 216, 125, 216],
       [216,  27, 729, 343],
       [ 27,   1, 216,  64]], dtype=int32)

In [167]:
np.mean(arr1)

5.416666666666667

In [168]:
np.std(arr1)

2.289771944005681

In [169]:
np.subtract(arr1, arr2) #arr1 - arr2

array([[ 6,  3,  3, -2],
       [ 1, -4,  6,  1],
       [-1, -6,  1, -5]])

In [170]:
arr1*arr2

array([[27, 18, 10, 48],
       [30, 21, 27, 42],
       [12,  7, 30, 36]])

In [171]:
arr1

array([[9, 6, 5, 6],
       [6, 3, 9, 7],
       [3, 1, 6, 4]])

In [172]:
np.mod(arr1, 5)  #modulo

array([[4, 1, 0, 1],
       [1, 3, 4, 2],
       [3, 1, 1, 4]], dtype=int32)

In [173]:
arr2

array([[3, 3, 2, 8],
       [5, 7, 3, 6],
       [4, 7, 5, 9]])

In [174]:
np.mod(arr1, arr2)  #index wise remainder

array([[0, 0, 1, 6],
       [1, 3, 0, 1],
       [3, 1, 1, 4]])

In [175]:
np.power(arr1, arr2)

array([[    729,     216,      25, 1679616],
       [   7776,    2187,     729,  117649],
       [     81,       1,    7776,  262144]])

In [176]:
np.sqrt(arr1)

array([[3.        , 2.44948974, 2.23606798, 2.44948974],
       [2.44948974, 1.73205081, 3.        , 2.64575131],
       [1.73205081, 1.        , 2.44948974, 2.        ]])

# sort search

In [177]:
arr=np.array([5,6,1,2])

In [178]:
arr

array([5, 6, 1, 2])

In [179]:
np.sort(arr) #does not sort the actual array

array([1, 2, 5, 6])

In [180]:
arr 

array([5, 6, 1, 2])

In [181]:
arr=np.array([5,6,100,200,1,2,8,9])

In [182]:
arr.sort() #this sorts the array internally

In [183]:
arr

array([  1,   2,   5,   6,   8,   9, 100, 200])

In [184]:
arr=np.array([5,6,100,200,1,2,8,9])

searchsorted(), what index to use to insert the passed number so as to maintain the order of the array.

In [189]:
np.searchsorted(arr,5) #for 5,6,100,200,1,2,8,9], it gives 6, meaning 5 should come after 2 (index 6 ) and before 8, current index 6

6

In [200]:
arr1 = np.array([0, 1, 2, 3, 0, 4])
np.count_nonzero(arr1)

4

In [192]:
arr1>0

array([False,  True,  True,  True, False,  True])

In [193]:
arr1

array([0, 1, 2, 3, 0, 4])

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied

In [194]:
np.where(arr1>0)

(array([1, 2, 3, 5], dtype=int64),)

In [195]:
np.where(arr1==0)

(array([0, 4], dtype=int64),)

In [196]:
arr

array([  5,   6, 100, 200,   1,   2,   8,   9])

The <h3>numpy.extract()</h3> function returns elements of input_array if they satisfy some specified condition.

In [198]:
np.extract(arr1>0, arr) # the conditon returns the indices from arr1, and those indices are being extracted from arr

array([  6, 100, 200,   2])

In [201]:
arr1.byteswap()  #byte representation of the data

array([       0, 16777216, 33554432, 50331648,        0, 67108864])