In [1]:
import numpy as np
import numpy.matlib as nm

In [2]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [6]:
nm.zeros((3,3))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# Numpy linear algebra

In [16]:
arr1 = np.array([[2, 3], [4, 5]])
arr2 = np.array([[1, 3], [4, 5]])

In [17]:
print(arr1,"\n \n \n\n", arr2)

[[2 3]
 [4 5]] 
 
 

 [[1 3]
 [4 5]]


In [19]:
arr1@arr2  #matrix multiplications

array([[14, 21],
       [24, 37]])

In [20]:
a  = np.array([[7, 5.3, -3], [3, -5, 2], [5, 3, -7]])

In [21]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [22]:
b=np.array([16,-8,0])

In [23]:
b

array([16, -8,  0])

## Solve for Ax = b, given a and b

In [27]:
x=np.linalg.solve(a,b)  #solves for ax=b
x

array([0.90162081, 2.89483603, 1.88465888])

In [33]:
a@x   #ax== b in terms of values

array([ 1.60000000e+01, -8.00000000e+00,  1.77635684e-15])

### Determinant using np.linalg

In [31]:
arr=np.random.randint(1,10, (3,3))
arr

array([[9, 1, 5],
       [9, 5, 2],
       [3, 4, 1]])

In [34]:
np.linalg.det(arr1)

-2.0

### Inverse of a matrix using np.linalg.inv()

In [37]:
inverse_arr1=np.linalg.inv(arr1)
inverse_arr1

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [39]:
arr1@inverse_arr1   #proof, A (1/A) =I

array([[1., 0.],
       [0., 1.]])