In [1]:
import numpy as np

Question 1

Question 2

Question 3

In [8]:
arr=np.arange(1,13).reshape(3,4)
print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 4)
12
2


Question 4

In [12]:
arr[0]

array([1, 2, 3, 4])

Question 5

In [13]:
arr[2,3]

12

Question 6

In [15]:
#assuming odd indexed means the index of a given element, including both row and column. like 11, 13, 21
arr[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

Question 7

In [20]:
np.random.rand(3,3)

array([[0.27663342, 0.97165688, 0.08641328],
       [0.15552792, 0.17424971, 0.8429944 ],
       [0.10936295, 0.01279679, 0.77573641]])

Question 8

np.random.rand generates a numpy array of the given shape where each element is from a uniform distribution over 0 and 1.

In [24]:
np.random.rand(1,10)

array([[0.24732066, 0.13612131, 0.54080555, 0.43192955, 0.60126032,
        0.72709184, 0.74522993, 0.3056183 , 0.13342899, 0.75055437]])

np.random.randn() generates a sample from the standard normal distribution, with mean 0 and variance 1

In [25]:
np.random.randn(10)

array([ 0.82168502,  1.47693504,  1.36816126,  0.14249028, -0.5020302 ,
        0.13586257, -1.36660366, -0.23414612,  2.26215102,  0.31327469])

Question 9

In [32]:
print(arr.ndim) #old dimension =2 
print(np.expand_dims(arr, axis=1).ndim) #New dimension: 3

2
3


Question 10

In [35]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Question 11